### ISSUE TITLE
wow

### ISSUE THREAD

**Issue by nitinthewiz** [lolnein/lolnein.github.io#1]
I **never** realized that your *comics* site is github pages. That's awesome! Between this and Cloudflare, it must be saving you a ton of money! (But now that i think about it, that was an odd thing for me to say. I only said it because it's rather interesting to me that I'm spending at least $5/mo on hosting on DigitalOcean and you've figured out a great way to save those dollars!)

What happened to the Climate change comic? Why did you remove it? It was funny enough... Besides, I was able to read it thanks to git remembering every single change you've ever made to the project 😆

**Comment by lolnein** [comment]
Thank you! All thanks to the guy who helped me start my webcomic and built my website! :)

The climate change comic was a bit too confusing, I guess. I might put it under the "Privacy Policy" comic (which was the "original" version) because I think more people will get it this way. But thank you, again! :)

**Comment by nitinthewiz** [comment]
Pretty awesome work indeed! Kudos to that person! 👍 

Fair enough, the comic might seem confusing to some. In context of your Privacy policy one, it was crystal clear and sadly funny... 😛 

Keep up the good work! 😄
